services:
  enu:
    image: mingfunwong/enu:1.7.3
    restart: always
    ports:
      - '8080:8080'
      - '9003:9003'
    environment:
      PRODUCER_ENABLE: 'false'
      PRODUCER_NAME:
      PUBLIC_KEY:
      PRIVATE_KEY:
      PRODUCER_API_ENABLE: 'false'
      SNAPSHOT_URL: https://github.com/andy-backup/enu/raw/master/snapshot.bin
    command: ['bash', '/enu/start.sh']
